# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    router:
        utf8: true
        strict_requirements: null

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
